FROM node:slim
RUN apt update
RUN apt install unzip wget -y
RUN wget https://github.com/jsososo/QQMusicApi/archive/refs/heads/master.zip
RUN unzip master.zip
WORKDIR /QQMusicApi-master
RUN yarn
WORKDIR /QQMusicApi-master
ENTRYPOINT [ "yarn" , "start" ]