import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React, { useEffect, useRef, useState } from 'react'
import { connection } from '../utils/music'

export default function Home() {
  const player = React.createRef<HTMLAudioElement>();

  const [id, setId] = useState("");
  const [src, setSrc] = useState("");
  const [playtime, setPlaytime] = useState(0);
  const [name, setName] = useState("");
  const [ar, setAr] = useState("");
  const [a, setA] = useState([]);

  const conn = useRef(new connection("http://43.138.39.172:81/music",
    async (params: { url: string, name: string, artist: string }, time: number) => {
      console.log(params);
      setSrc(params.url);
      setName(params.name);
      setAr(params.artist);
      setPlaytime(time);
      console.log("Played: " + time);
      const b = await conn.current.getPlayList();
      console.log(b);
      setA(b);
    }, async () => {
      const b = await conn.current.getPlayList();
      console.log(b);
      setA(b);
    }));
  useEffect(() => {
    conn.current.start();
  }, [conn]);
  useEffect(() => {
    // @ts-ignore
    player.current.currentTime = playtime;
  }, [playtime])


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <div className={styles.description}>
          {`Now Playing: ${name} - ${ar}`}
        </div>

        <div className={styles.card}>
          <p className={styles.description}>Queue</p>
          <ul>
            {a.map((v: { name: string, artist: string }) => {
              return (
                <li key={v.name}>
                  {v.name} - {v.artist}
                </li>
              )
            })}
          </ul>
        </div>

        <audio src={src} controls ref={player} autoPlay />

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div>
          <input type={"text"} value={id} placeholder={"type music id here"} onChange={e => {
            setId(e.target.value);
          }} />
          <button onClick={() => {
            conn.current.addMusicToPlayList(id).then(ok => {
              if (ok) {
                console.log("ok");
              } else {
                console.log("failed");
              }
            }).catch(err => console.log(err));
          }}>
            Enqueue
          </button>
        </div>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
